import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const templateRoot = new URL("../", import.meta.url);
const previewRoot = new URL("../app/_sites-preview/", import.meta.url);

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the Slater Woods Omni Design startup dashboard", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Slater Woods Omni Design<\/title>/i);
  assert.match(html, /Slater Woods Omni Design/);
  assert.match(html, /aria-label="Program menu"/);
  assert.match(html, /aria-label="Quick access"/);
  assert.match(html, /app-shell theme-light is-dashboard/);
  assert.match(html, /aria-label="Switch to dark mode"/);
  assert.match(html, />Light</);
  assert.match(html, /aria-label="Save project as"/);
  assert.match(html, /aria-label="Application menus"/);
  assert.match(html, />File</);
  assert.match(html, />Edit</);
  assert.match(html, />Window</);
  assert.match(html, />Tools</);
  assert.match(html, />Help</);
  assert.match(html, /aria-label="Open projects"/);
  assert.match(html, /aria-label="Slater Woods Omni Design dashboard"/);
  assert.match(html, />Omni Design</);
  assert.match(html, /Begin a project/);
  assert.match(html, />New Plan</);
  assert.match(html, /Blank model in 2D Top view/);
  assert.match(html, /Pick up where you left off/);
  assert.match(html, /No recent projects yet/);
  assert.match(html, /Local convenience copies/);
  assert.match(html, /Recommended workflow/);
  assert.match(html, /Project settings/);
  assert.match(html, /Foundation and layered wall types/);
  assert.match(html, /Help and reference/);
  assert.match(html, /Local recovery is active/);
  assert.doesNotMatch(html, /aria-label="Tool categories"|aria-label="Model and layouts"|aria-label="Command input"/);
  assert.match(html, /aria-label="Project name"/);
  assert.match(html, /title="New blank plan"/);
  assert.match(html, /accept="\.mbproj,application\/json"/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});

test("keeps product code separate from the removed starter preview", async () => {
  const [page, layout, component, productLibraryDialog, productRepresentationRenderer, productRepresentations, materialLibrary, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/model-builder-app.tsx", import.meta.url), "utf8"),
    readFile(new URL("../features/products/product-library-dialog.tsx", import.meta.url), "utf8"),
    readFile(new URL("../features/products/product-representation-renderer.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/product-representations.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/material-library.ts", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /import \{ ModelBuilderApp \}/);
  assert.match(page, /<ModelBuilderApp \/>/);
  assert.match(layout, /title:\s*"Slater Woods Omni Design"/);
  assert.match(component, /"use client"/);
  assert.match(component, /from "@\/features\/products\/product-library-dialog"/);
  assert.match(component, /from "@\/features\/products\/product-representation-renderer"/);
  assert.doesNotMatch(component, /function ProductLibraryDialog/);
  assert.match(productLibraryDialog, /export function ProductLibraryDialog/);
  assert.match(productLibraryDialog, /Representation Alignment/);
  assert.match(productLibraryDialog, /New Object Type/);
  assert.match(productLibraryDialog, /Place on Current Layer/);
  assert.match(component, /addProductObject/);
  assert.match(productRepresentationRenderer, /applyPreferredProductRepresentations/);
  assert.match(productRepresentationRenderer, /native parametric components remain visible/);
  assert.match(productRepresentations, /preferredProductAssetForView/);
  assert.match(component, /from "three"/);
  assert.match(component, /OrthographicCamera/);
  assert.match(component, /changeViewTarget/);
  assert.match(component, /NavigationCube/);
  assert.match(component, /CubeOrbitController/);
  assert.match(component, /is-orbiting/);
  assert.match(component, /skipNextViewApplyRef/);
  assert.match(component, /navigationTargetFromDirection/);
  assert.match(component, /CameraTransition/);
  assert.match(component, /prefers-reduced-motion/);
  assert.match(component, /slerpQuaternions/);
  assert.match(component, /Standard views · orthographic/);
  assert.match(component, /parseArchitectural/);
  assert.match(component, /parseSignedArchitectural/);
  assert.match(component, /moveBoxFace/);
  assert.match(component, /moveBoxObject/);
  assert.match(component, /moveBoxObjects/);
  assert.match(component, /alignBoxObjects/);
  assert.match(component, /deleteBoxObjects/);
  assert.match(component, /groupBoxObjects/);
  assert.match(component, /ungroupBoxObjects/);
  assert.match(component, /setBoxObjectsLocked/);
  assert.match(component, /selectionIdsForObject/);
  assert.match(component, /Selection locked/);
  assert.match(component, /PropertyGridSection/);
  assert.match(component, /PropertyGridRow/);
  assert.match(component, /layer-grid/);
  assert.match(component, /Search layers/);
  assert.match(component, /copyBoxObjects/);
  assert.match(component, /CopyObjectsControl/);
  assert.match(component, /Copy active/);
  assert.match(component, /moveModelEntities/);
  assert.match(component, /copyModelEntities/);
  assert.match(component, /deleteModelEntities/);
  assert.match(component, /rotateModelEntities/);
  assert.match(component, /modelSelectionRotationBase/);
  assert.match(component, /scaleModelEntities/);
  assert.match(component, /modelSelectionScaleBase/);
  assert.match(component, /ScaleControl/);
  assert.match(component, /mirrorModelEntities/);
  assert.match(component, /MirrorControl/);
  assert.match(component, /onMirrorCommit/);
  assert.match(component, /offsetModelEntity/);
  assert.match(component, /OffsetControl/);
  assert.match(component, /onOffsetCommit/);
  assert.match(component, /trimModelEntity/);
  assert.match(component, /extendModelEntity/);
  assert.match(component, /TrimExtendControl/);
  assert.match(component, /onTrimExtendCommit/);
  assert.match(component, /breakModelEntity/);
  assert.match(component, /BreakControl/);
  assert.match(component, /onBreakCommit/);
  assert.match(component, /joinModelEntities/);
  assert.match(component, /JoinControl/);
  assert.match(component, /explodeModelEntities/);
  assert.match(component, /ExplodeControl/);
  assert.match(component, /lengthenModelEntity/);
  assert.match(component, /LengthenControl/);
  assert.match(component, /onLengthenCommit/);
  assert.match(component, /chamferLineObjects/);
  assert.match(component, /chamferPolylineObject/);
  assert.match(component, /Chamfer Polyline/);
  assert.match(component, /ChamferControl/);
  assert.match(component, /onChamferCommit/);
  assert.match(component, /filletCurveObjects/);
  assert.match(component, /filletPolylineObject/);
  assert.match(component, /Fillet Polyline/);
  assert.match(component, /FilletControl/);
  assert.match(component, /onFilletCommit/);
  assert.match(component, /discoverDocumentBoundary/);
  assert.match(component, /createBoundaryPolylineObject/);
  assert.match(component, /onBoundaryCommit/);
  assert.match(component, /StoryManagerDialog/);
  assert.match(component, /AssemblyMaterialSelect/);
  assert.match(component, /Current project material/);
  assert.match(component, /MATERIAL_CATEGORY_LABELS/);
  assert.doesNotMatch(component, /material: "New Material"/);
  assert.match(materialLibrary, /ARCHITECTURAL_MATERIALS/);
  assert.match(materialLibrary, /textureAssetId: string \| null/);
  assert.match(materialLibrary, /architecturalMaterialsForRole/);
  assert.match(component, /Rough framing establishes reference elevations/);
  assert.match(component, /ELEVATION REFERENCE/);
  assert.match(component, /label="Reference elevation"/);
  assert.doesNotMatch(component, /Datum elevation|Datum anchor|Set as datum anchor/);
  assert.match(component, /className="story-wall-group-add"/);
  assert.doesNotMatch(component, /story-add-wall-layers/);
  assert.match(component, /aria-label="Active Wall Type for new walls"/);
  assert.match(component, /aria-label="Wall Use for new walls"/);
  assert.match(component, /Interior Bearing Wall/);
  assert.match(component, /aria-label="Project active Wall Type"/);
  assert.match(component, /const trackingAnchor = source/);
  assert.match(component, /drag\.objectId,[\s\S]*trackingAnchor,[\s\S]*true,/);
  assert.match(component, /updateDocumentBuilding/);
  assert.match(component, /calculateStoryElevations/);
  assert.match(component, /RoomManagerDialog/);
  assert.match(component, /OpeningTypeManagerDialog/);
  assert.match(component, /Door &amp; Window Type Manager/);
  assert.match(component, /Header Assembly Definition/);
  assert.match(component, /Duplicate &amp; Assign/);
  assert.match(component, /Rigid insulation at interior/);
  assert.match(component, /Spacers between plies/);
  assert.match(component, /Main thickness required/);
  assert.match(component, /assignWallOpeningType/);
  assert.match(component, /wallOpeningTypeId/);
  assert.match(component, /WallFramingManagerDialog/);
  assert.match(component, /Wall Framing Defaults/);
  assert.match(component, /wallFramingSolids/);
  assert.match(component, /Show framing in the 3D model/);
  assert.match(component, /Three-stud conventional/);
  assert.match(component, /Ladder blocking/);
  assert.match(component, /Detect \/ Update Rooms/);
  assert.match(component, /refreshRoomsForStory/);
  assert.match(component, /wallVerticalExtent/);
  assert.match(component, /foundationWallVerticalExtent/);
  assert.match(component, /createFoundationWallFromLine/);
  assert.match(component, /buildAutomaticFoundationWallJoinPlan/);
  assert.match(component, /Supporting Foundation Wall/);
  assert.match(component, /base and top automatically follow adjacent Room rough conditions/);
  assert.match(component, /roomHorizontalPlatformSolution/);
  assert.match(component, /Generated Room platforms/);
  assert.match(component, /Generated finished ceiling/);
  assert.match(component, /Platform Openings/);
  assert.match(component, /addPlatformOpening/);
  assert.match(component, /updatePlatformOpening/);
  assert.match(component, /continuePlatformOpening/);
  assert.match(component, /Disconnect Path/);
  assert.match(component, /Vertical path/);
  assert.match(component, /room\.platformOpenings/);
  assert.match(component, /building-browser/);
  assert.match(component, /Project Setup/);
  assert.match(component, /Building standards · saved with project/);
  assert.match(component, /Documentation standards · saved with project/);
  assert.match(component, /Application preferences · follows user/);
  assert.match(component, /Floors &amp;/);
  assert.match(component, /Layer<br \/>Properties/);
  assert.match(component, /className="is-planned" disabled/);
  assert.match(component, /Confirm project settings/);
  assert.match(component, /saveProjectAs/);
  assert.match(component, /File and application commands/);
  assert.match(component, /aria-label="Command line"/);
  assert.match(component, /className="commandbar-shell"/);
  assert.match(component, /className="model-space-indicator"/);
  assert.match(component, /aria-label="Drafting status controls"/);
  assert.match(component, /aria-pressed=\{cadDraftingSettings\.objectSnapEnabled\}/);
  assert.doesNotMatch(component, /Command history|Model and layouts|Layouts are planned|space-menu/);
  assert.match(component, /3D Perspective/);
  assert.match(component, /onClick=\{\(\) => onNavigate\(VIEW_PRESETS\.top\)\}/);
  assert.match(component, /Model Explorer · Building/);
  assert.match(component, /stretchModelEntities/);
  assert.match(component, /selectScreenStretchTargets/);
  assert.match(component, /StretchControl/);
  assert.match(component, /onStretchCommit/);
  assert.match(component, /AlignmentControl/);
  assert.match(component, /Shift-click/);
  assert.match(component, /snapObjectMoveDistance/);
  assert.match(component, /createMoveGizmo/);
  assert.match(component, /createRotationGizmo/);
  assert.match(component, /snapRotationAngle/);
  assert.match(component, /RotationControl/);
  assert.match(component, /rotateMode/);
  assert.match(component, /addLineObject/);
  assert.match(component, /addCircleObject/);
  assert.match(component, /createViewportCircle/);
  assert.match(component, /createCircleGripSet/);
  assert.match(component, /CircleGeometryControl/);
  assert.match(component, /CircleViewportCommand/);
  assert.match(component, /circleMode/);
  assert.match(component, /Circle construction method/);
  assert.match(component, /circleFromCenterDiameter/);
  assert.match(component, /circleFromDiameterPoints/);
  assert.match(component, /circleFromThreePoints/);
  assert.match(component, /addArcObject/);
  assert.match(component, /createViewportArc/);
  assert.match(component, /createArcGripSet/);
  assert.match(component, /ArcGeometryControl/);
  assert.match(component, /ArcViewportCommand/);
  assert.match(component, /arcMode/);
  assert.match(component, /Arc construction method/);
  assert.match(component, /start-center-angle/);
  assert.match(component, /start-end-direction/);
  assert.match(component, /center-start-length/);
  assert.match(component, /continueSeedFromReference/);
  assert.match(component, /createViewportLine/);
  assert.match(component, /createLineGripSet/);
  assert.match(component, /LineGeometryControl/);
  assert.match(component, /lineFromLengthAngle/);
  assert.match(component, /lineFromDirection/);
  assert.match(component, /parseLineCoordinate/);
  assert.match(component, /acquireCadPoint/);
  assert.match(component, /derivedSnapCandidates/);
  assert.match(component, /selectScreenGeometries/);
  assert.match(component, /visibleCadEntityRefs/);
  assert.match(component, /cad-selection-window/);
  assert.match(component, /onSelectionWindow/);
  assert.match(component, /advanceSelectionCycle/);
  assert.match(component, /hoveredEntityKey/);
  assert.match(component, /cad-selection-cycle/);
  assert.match(component, /Click again or press Tab to cycle/);
  assert.match(component, /line-dynamic-input/);
  assert.match(component, /activePreviewMode/);
  assert.match(component, /onLineUndoSegment/);
  assert.match(component, /CAD_DRAFTING_SETTINGS_STORAGE_KEY/);
  assert.match(component, /gridVisible/);
  assert.match(component, /event\.key === "F7"/);
  assert.match(component, /plan-ucs-x/);
  assert.doesNotMatch(component, /new THREE\.AxesHelper/);
  assert.match(component, /INTERFACE_THEME_STORAGE_KEY/);
  assert.match(component, /useSyncExternalStore/);
  assert.match(component, /interfaceTheme={interfaceTheme}/);
  assert.match(component, /Additional line snap angles/);
  assert.match(component, /Start Z/);
  assert.match(component, /lineMode/);
  assert.match(component, /addPolylineObject/);
  assert.match(component, /createViewportPolyline/);
  assert.match(component, /createPolylineGripSet/);
  assert.match(component, /rectangleFromCorners/);
  assert.match(component, /parseRectangleDimensionPair/);
  assert.match(component, /rectangleFromDimensions/);
  assert.match(component, /RectangleGeometryControl/);
  assert.match(component, /rectangleGripPoints/);
  assert.match(component, /updatePolylineObjectGrip/);
  assert.match(component, /RectangleViewportCommand/);
  assert.match(component, /PolylineViewportCommand/);
  assert.match(component, /dynamicPolylineInput/);
  assert.match(component, /onPolylineAnchorChange/);
  assert.match(component, /PolylineGeometryControl/);
  assert.match(component, /polylineCommand/);
  assert.match(component, /polylineBulgeFromThreePoints/);
  assert.match(component, /polylinePathPoints/);
  assert.match(component, /polylineSegmentMode/);
  assert.match(component, /Polyline constant width/);
  assert.match(component, /Line canceled\. Press Enter to repeat Line\./);
  assert.match(component, /Rectangle canceled\./);
  assert.match(component, /Polyline canceled\./);
  assert.match(component, /polylineMode/);
  assert.match(component, /rectangleMode/);
  assert.match(component, /2D creation · planned/);
  assert.match(component, /createBoxGripSet/);
  assert.match(component, /objectMoveGrip/);
  assert.match(component, /"plan-move"/);
  assert.match(component, /BOX_GRIP_DEFINITIONS/);
  assert.match(component, /resizeBoxFromGrip/);
  assert.match(component, /Exact face grip distance/);
  assert.match(component, /parseSignedArchitectural\(gripDraft\)/);
  assert.match(component, /Object face snap/);
  assert.match(component, /setBoxObjectPosition/);
  assert.match(component, /renameBoxObject/);
  assert.match(component, /EditableObjectName/);
  assert.match(component, /deleteBoxObject/);
  assert.match(component, /addLayer/);
  assert.match(component, /assignObjectToLayer/);
  assert.match(component, /toggleLayerVisibility/);
  assert.match(component, /toggleLayerLock/);
  assert.match(component, /LayerNameField/);
  assert.match(component, /You can restore it with Undo/);
  assert.match(component, /addBoxObject/);
  assert.match(component, /updateBoxObject/);
  assert.match(component, /projectToDocument/);
  assert.match(component, /commit-preview/);
  assert.match(component, /createProjectDocument/);
  assert.match(component, /parseProjectDocument/);
  assert.match(component, /parseRecoverySnapshot/);
  assert.match(component, /PROJECT_RECOVERY_STORAGE_KEY/);
  assert.match(component, /window\.localStorage/);
  assert.match(component, /pagehide/);
  assert.match(component, /beforeunload/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  await assert.rejects(access(new URL("SkeletonPreview.tsx", previewRoot)));
  await assert.rejects(access(new URL("preview.css", previewRoot)));
  await assert.rejects(access(new URL("public/_sites-preview", templateRoot)));
});
