import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const templateRoot = new URL("../", import.meta.url);
const previewRoot = new URL("../app/_sites-preview/", import.meta.url);

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the Model Builder workspace", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Model Builder<\/title>/i);
  assert.match(html, /2D \+ 3D Modeling/);
  assert.match(html, /aria-label="Tool categories"/);
  assert.match(html, /aria-label="Program menu"/);
  assert.match(html, /aria-label="Quick access"/);
  assert.match(html, /app-shell theme-light/);
  assert.match(html, /aria-label="Switch to dark mode"/);
  assert.match(html, />Light</);
  assert.match(html, /aria-label="Save project as"/);
  assert.match(html, /aria-label="Application menus"/);
  assert.match(html, />File</);
  assert.match(html, />Edit</);
  assert.match(html, />Window</);
  assert.match(html, />Tools</);
  assert.match(html, />Help</);
  assert.match(html, /ribbon ribbon-home/);
  assert.match(html, /home-modify-group/);
  assert.match(html, />Home</);
  assert.match(html, />Draw</);
  assert.match(html, />Model</);
  assert.match(html, />Annotate</);
  assert.match(html, />View</);
  assert.match(html, />Manage</);
  assert.match(html, /MODEL EXPLORER/);
  assert.match(html, /aria-label="Model explorer views"/);
  assert.match(html, />Building</);
  assert.match(html, /aria-label="New plan workflow"/);
  assert.match(html, /Set the building defaults, then draw the plan/);
  assert.match(html, /Stories, floors, and ceilings/);
  assert.match(html, /Exterior, Main, and Interior layers/);
  assert.match(html, /aria-label="Open projects"/);
  assert.match(html, /aria-label="Model and layouts"/);
  assert.match(html, /aria-label="Command input"/);
  assert.match(html, /Type W, L, PL, REC, C, A, BOUNDARY, M, CO, MI, O, TR, EX, BR, BP, J, X, LEN, CHA, F, S, RO, or SC/);
  assert.match(html, />\+ Wall</);
  assert.match(html, /Remove the portion between two points on a native curve/);
  assert.match(html, /Split an open native curve at one point/);
  assert.match(html, /Join endpoint-connected Lines, Arcs, and open Polylines into one native curve/);
  assert.match(html, /Explode selected Rectangles and Polylines into native Lines and Arcs/);
  assert.match(html, /Lengthen one Line, Arc, or open Polyline by Delta, Total, Percent, or Dynamic/);
  assert.match(html, /Chamfer two Lines or every corner of one selected Polyline/);
  assert.match(html, /Fillet Lines, Arcs, or every corner of one selected Polyline/);
  assert.match(html, /Create a closed Polyline from a visible enclosed area/);
  assert.match(html, /Precision 3D modeling in U\.S\. architectural units/);
  assert.match(html, /aria-label="3D navigation cube"/);
  assert.match(html, /aria-label="Home — Top plan view"/);
  assert.match(html, /aria-label="Toggle model space grid"/);
  assert.match(html, /title="Grid Display \(F7\)"/);
  assert.match(html, /GRID <small>1&#x27;-0&quot;<\/small>/);
  assert.match(html, /plan-ucs/);
  assert.doesNotMatch(html, /axis-z/);
  assert.match(html, /Snap <!-- -->1\/16&quot;/);
  assert.match(html, /Object Snap \(F3\)/);
  assert.match(html, /Ortho Mode \(F8\)/);
  assert.match(html, /Polar Tracking \(F10\)/);
  assert.match(html, /Draw exact 2D or 3D line segments/);
  assert.match(html, /title="Draw one connected polyline entity"/);
  assert.match(html, /title="Draw a closed rectangular polyline"/);
  assert.match(html, /title="Draw Circle: Center, Radius"/);
  assert.match(html, /title="Draw Arc: 3-Point"/);
  assert.match(html, />No selection</);
  assert.match(html, />Drawing properties</);
  assert.match(html, /Top · Orthographic/);
  assert.match(html, />New Plan</);
  assert.match(html, /property-grid-section/);
  assert.match(html, /property-table-row/);
  assert.match(html, />Erase</);
  assert.doesNotMatch(html, /Box 01|Selected box|aria-label="Object name"|aria-label="Selected object actions"/);
  assert.match(html, /aria-label="Project name"/);
  assert.match(html, /title="New blank plan"/);
  assert.match(html, /title="Open project \(Ctrl\+O\)"/);
  assert.match(html, /title="Save project \(Ctrl\+S\)"/);
  assert.match(html, /title="Add a parametric box"/);
  assert.match(html, /aria-label="Project objects"/);
  assert.match(html, /\+ Box/);
  assert.match(html, /0(?:<!-- -->)? BOX/);
  assert.match(html, /accept="\.mbproj,application\/json"/);
  assert.match(html, /RECOVERY ON/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});

test("keeps product code separate from the removed starter preview", async () => {
  const [page, layout, component, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/model-builder-app.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /import \{ ModelBuilderApp \}/);
  assert.match(page, /<ModelBuilderApp \/>/);
  assert.match(layout, /title:\s*"Model Builder"/);
  assert.match(component, /"use client"/);
  assert.match(component, /from "three"/);
  assert.match(component, /OrthographicCamera/);
  assert.match(component, /changeViewTarget/);
  assert.match(component, /NavigationCube/);
  assert.match(component, /CubeOrbitController/);
  assert.match(component, /is-orbiting/);
  assert.match(component, /skipNextViewApplyRef/);
  assert.match(component, /navigationTargetFromDirection/);
  assert.match(component, /CameraTransition/);
  assert.match(component, /prefers-reduced-motion/);
  assert.match(component, /slerpQuaternions/);
  assert.match(component, /Standard views · orthographic/);
  assert.match(component, /parseArchitectural/);
  assert.match(component, /parseSignedArchitectural/);
  assert.match(component, /moveBoxFace/);
  assert.match(component, /moveBoxObject/);
  assert.match(component, /moveBoxObjects/);
  assert.match(component, /alignBoxObjects/);
  assert.match(component, /deleteBoxObjects/);
  assert.match(component, /groupBoxObjects/);
  assert.match(component, /ungroupBoxObjects/);
  assert.match(component, /setBoxObjectsLocked/);
  assert.match(component, /selectionIdsForObject/);
  assert.match(component, /Selection locked/);
  assert.match(component, /PropertyGridSection/);
  assert.match(component, /PropertyGridRow/);
  assert.match(component, /layer-grid/);
  assert.match(component, /Search layers/);
  assert.match(component, /copyBoxObjects/);
  assert.match(component, /CopyObjectsControl/);
  assert.match(component, /Copy active/);
  assert.match(component, /moveModelEntities/);
  assert.match(component, /copyModelEntities/);
  assert.match(component, /deleteModelEntities/);
  assert.match(component, /rotateModelEntities/);
  assert.match(component, /modelSelectionRotationBase/);
  assert.match(component, /scaleModelEntities/);
  assert.match(component, /modelSelectionScaleBase/);
  assert.match(component, /ScaleControl/);
  assert.match(component, /mirrorModelEntities/);
  assert.match(component, /MirrorControl/);
  assert.match(component, /onMirrorCommit/);
  assert.match(component, /offsetModelEntity/);
  assert.match(component, /OffsetControl/);
  assert.match(component, /onOffsetCommit/);
  assert.match(component, /trimModelEntity/);
  assert.match(component, /extendModelEntity/);
  assert.match(component, /TrimExtendControl/);
  assert.match(component, /onTrimExtendCommit/);
  assert.match(component, /breakModelEntity/);
  assert.match(component, /BreakControl/);
  assert.match(component, /onBreakCommit/);
  assert.match(component, /joinModelEntities/);
  assert.match(component, /JoinControl/);
  assert.match(component, /explodeModelEntities/);
  assert.match(component, /ExplodeControl/);
  assert.match(component, /lengthenModelEntity/);
  assert.match(component, /LengthenControl/);
  assert.match(component, /onLengthenCommit/);
  assert.match(component, /chamferLineObjects/);
  assert.match(component, /chamferPolylineObject/);
  assert.match(component, /Chamfer Polyline/);
  assert.match(component, /ChamferControl/);
  assert.match(component, /onChamferCommit/);
  assert.match(component, /filletCurveObjects/);
  assert.match(component, /filletPolylineObject/);
  assert.match(component, /Fillet Polyline/);
  assert.match(component, /FilletControl/);
  assert.match(component, /onFilletCommit/);
  assert.match(component, /discoverDocumentBoundary/);
  assert.match(component, /createBoundaryPolylineObject/);
  assert.match(component, /onBoundaryCommit/);
  assert.match(component, /StoryManagerDialog/);
  assert.match(component, /Rough framing establishes vertical datums/);
  assert.match(component, /updateDocumentBuilding/);
  assert.match(component, /calculateStoryElevations/);
  assert.match(component, /RoomManagerDialog/);
  assert.match(component, /Detect \/ Update Rooms/);
  assert.match(component, /refreshRoomsForStory/);
  assert.match(component, /wallVerticalExtent/);
  assert.match(component, /base and top automatically follow adjacent Room rough conditions/);
  assert.match(component, /building-browser/);
  assert.match(component, /Project Setup/);
  assert.match(component, /Building standards · saved with project/);
  assert.match(component, /Documentation standards · saved with project/);
  assert.match(component, /Application preferences · follows user/);
  assert.match(component, /Floors &amp;/);
  assert.match(component, /Layer<br \/>Properties/);
  assert.match(component, /className="is-planned" disabled/);
  assert.match(component, /Confirm project settings/);
  assert.match(component, /saveProjectAs/);
  assert.match(component, /File and application commands/);
  assert.match(component, /3D Perspective/);
  assert.match(component, /onClick=\{\(\) => onNavigate\(VIEW_PRESETS\.top\)\}/);
  assert.match(component, /Model Explorer · Building/);
  assert.match(component, /stretchModelEntities/);
  assert.match(component, /selectScreenStretchTargets/);
  assert.match(component, /StretchControl/);
  assert.match(component, /onStretchCommit/);
  assert.match(component, /AlignmentControl/);
  assert.match(component, /Shift-click/);
  assert.match(component, /snapObjectMoveDistance/);
  assert.match(component, /createMoveGizmo/);
  assert.match(component, /createRotationGizmo/);
  assert.match(component, /snapRotationAngle/);
  assert.match(component, /RotationControl/);
  assert.match(component, /rotateMode/);
  assert.match(component, /addLineObject/);
  assert.match(component, /addCircleObject/);
  assert.match(component, /createViewportCircle/);
  assert.match(component, /createCircleGripSet/);
  assert.match(component, /CircleGeometryControl/);
  assert.match(component, /CircleViewportCommand/);
  assert.match(component, /circleMode/);
  assert.match(component, /Circle construction method/);
  assert.match(component, /circleFromCenterDiameter/);
  assert.match(component, /circleFromDiameterPoints/);
  assert.match(component, /circleFromThreePoints/);
  assert.match(component, /addArcObject/);
  assert.match(component, /createViewportArc/);
  assert.match(component, /createArcGripSet/);
  assert.match(component, /ArcGeometryControl/);
  assert.match(component, /ArcViewportCommand/);
  assert.match(component, /arcMode/);
  assert.match(component, /Arc construction method/);
  assert.match(component, /start-center-angle/);
  assert.match(component, /start-end-direction/);
  assert.match(component, /center-start-length/);
  assert.match(component, /continueSeedFromReference/);
  assert.match(component, /createViewportLine/);
  assert.match(component, /createLineGripSet/);
  assert.match(component, /LineGeometryControl/);
  assert.match(component, /lineFromLengthAngle/);
  assert.match(component, /lineFromDirection/);
  assert.match(component, /parseLineCoordinate/);
  assert.match(component, /acquireCadPoint/);
  assert.match(component, /derivedSnapCandidates/);
  assert.match(component, /selectScreenGeometries/);
  assert.match(component, /visibleCadEntityRefs/);
  assert.match(component, /cad-selection-window/);
  assert.match(component, /onSelectionWindow/);
  assert.match(component, /advanceSelectionCycle/);
  assert.match(component, /hoveredEntityKey/);
  assert.match(component, /cad-selection-cycle/);
  assert.match(component, /Click again or press Tab to cycle/);
  assert.match(component, /line-dynamic-input/);
  assert.match(component, /activePreviewMode/);
  assert.match(component, /onLineUndoSegment/);
  assert.match(component, /CAD_DRAFTING_SETTINGS_STORAGE_KEY/);
  assert.match(component, /gridVisible/);
  assert.match(component, /event\.key === "F7"/);
  assert.match(component, /plan-ucs-x/);
  assert.doesNotMatch(component, /new THREE\.AxesHelper/);
  assert.match(component, /INTERFACE_THEME_STORAGE_KEY/);
  assert.match(component, /useSyncExternalStore/);
  assert.match(component, /interfaceTheme={interfaceTheme}/);
  assert.match(component, /Additional line snap angles/);
  assert.match(component, /Start Z/);
  assert.match(component, /lineMode/);
  assert.match(component, /addPolylineObject/);
  assert.match(component, /createViewportPolyline/);
  assert.match(component, /createPolylineGripSet/);
  assert.match(component, /rectangleFromCorners/);
  assert.match(component, /parseRectangleDimensionPair/);
  assert.match(component, /rectangleFromDimensions/);
  assert.match(component, /RectangleGeometryControl/);
  assert.match(component, /rectangleGripPoints/);
  assert.match(component, /updatePolylineObjectGrip/);
  assert.match(component, /RectangleViewportCommand/);
  assert.match(component, /PolylineViewportCommand/);
  assert.match(component, /dynamicPolylineInput/);
  assert.match(component, /onPolylineAnchorChange/);
  assert.match(component, /PolylineGeometryControl/);
  assert.match(component, /polylineCommand/);
  assert.match(component, /polylineBulgeFromThreePoints/);
  assert.match(component, /polylinePathPoints/);
  assert.match(component, /polylineSegmentMode/);
  assert.match(component, /Polyline constant width/);
  assert.match(component, /Line canceled\. Press Enter to repeat Line\./);
  assert.match(component, /Rectangle canceled\./);
  assert.match(component, /Polyline canceled\./);
  assert.match(component, /polylineMode/);
  assert.match(component, /rectangleMode/);
  assert.match(component, /2D creation · planned/);
  assert.match(component, /createBoxGripSet/);
  assert.match(component, /objectMoveGrip/);
  assert.match(component, /"plan-move"/);
  assert.match(component, /BOX_GRIP_DEFINITIONS/);
  assert.match(component, /resizeBoxFromGrip/);
  assert.match(component, /Exact face grip distance/);
  assert.match(component, /parseSignedArchitectural\(gripDraft\)/);
  assert.match(component, /Object face snap/);
  assert.match(component, /setBoxObjectPosition/);
  assert.match(component, /renameBoxObject/);
  assert.match(component, /EditableObjectName/);
  assert.match(component, /deleteBoxObject/);
  assert.match(component, /addLayer/);
  assert.match(component, /assignObjectToLayer/);
  assert.match(component, /toggleLayerVisibility/);
  assert.match(component, /toggleLayerLock/);
  assert.match(component, /LayerNameField/);
  assert.match(component, /You can restore it with Undo/);
  assert.match(component, /addBoxObject/);
  assert.match(component, /updateBoxObject/);
  assert.match(component, /projectToDocument/);
  assert.match(component, /commit-preview/);
  assert.match(component, /createProjectDocument/);
  assert.match(component, /parseProjectDocument/);
  assert.match(component, /parseRecoverySnapshot/);
  assert.match(component, /PROJECT_RECOVERY_STORAGE_KEY/);
  assert.match(component, /window\.localStorage/);
  assert.match(component, /pagehide/);
  assert.match(component, /beforeunload/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  await assert.rejects(access(new URL("SkeletonPreview.tsx", previewRoot)));
  await assert.rejects(access(new URL("preview.css", previewRoot)));
  await assert.rejects(access(new URL("public/_sites-preview", templateRoot)));
});
