import { env } from "cloudflare:workers";
import { drizzle } from "drizzle-orm/d1";
import * as schema from "./schema";

// `Cloudflare.Env` is normally generated by `wrangler types` from a wrangler
// config. This project has no wrangler config checked in, so declare the one
// binding this module needs. It is optional because the runtime check in
// getDb() is what actually enforces its presence.
declare global {
  namespace Cloudflare {
    interface Env {
      DB?: D1Database;
    }
  }
}

export function getDb() {
  if (!env.DB) {
    throw new Error(
      "Cloudflare D1 binding `DB` is unavailable. Set the `d1` field in .openai/hosting.json to `DB` or let your control plane inject the real binding values before using the database."
    );
  }

  return drizzle(env.DB, { schema });
}
